# Config file

refs : ["AJ717293_1", "AY083234_1", "DQ333427_1", "DQ357065_1", "FN669502_1", "HQ340602_1",
"NC_000883_2", "NC_001540_1", "NC_004295_1"]

# refs: ["AY083234_1", "NC_004295_1", "AJ717293_1"]

mapping_quality: [0, 1, 10, 30]

samples: ../samples_24botocudos.txt

path2_read_length: "/scratch/axiom/FAC/FBM/DBC/amalaspi/virome/yarizmen/virome/Botocudos-scripts/\
DataQuality/read_length.py"