###To make the projection of the samples using lsqproject the plink files for the reference panel and the samples have to be merged

###For the sample use the files: *filt_sites.ped and *filt_sites.map (generated by make_evec.....sh)
###and make a recode of those files if your reference panel is in plink files .bim .bed , if not, continue
###
#Your job name
#$ -N plink_merge_ped_lsq
#Use current working directory
#$ -cwd

#Join stdout and stderr
#$ -j y
# Run job through bash shell
#$ -S /bin/bash

#Send an email after the job has finished
#$ -m e
#$ -M villa.islas.vi@gmail.com

#If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh


module load plink/1.07

###Make the merging of the reference panel plink files and the .ped .map plink files of the sample
###merge_list.txt contains the complete name of the .ped .map files of the sample separeted by one space
###if more than one sample will be merged with the reference panel plink files, they have to be separated by a new line
orig_panel=America_Oceania
panel=merged_AmOc

ind=MA2382

plink --file $orig_panel --merge $ind.hg19_nuc.realigned.America_Oceania.filt_sites.ped \
$ind.hg19_nuc.realigned.America_Oceania.filt_sites.map \
--make-bed --out $panel --allow-no-sex --geno 0.007

plink --file $orig_panel --merge-list merge_list2.txt \
--make-bed --out $panel --allow-no-sex --geno 0.015


##make the recode of files basename_of_output_file

plink --bfile $panel --recode --out $panel


###For lsqproject it is necessary to edit the basename_of_output_file.ped file in order to indicate which individuals belong to the reference panel and which belong to the samples

awk '{print $1,"REF"}' $panel.fam  > $panel.poplist

#It is necessary to modify manually the second column of the list "basename_of_output_file.poplist" to substitute "REF" for "SAMPLE" in the samples.
##Save the changes in the same file basename_of_output_file.poplist
##Add a new column indicating REF or SAMPLE to ped file. To modify ped file:

sed -i 's/.hg.* REF/ SAMPLE/' $panel.poplist


sed -i 's/MA.*realigned M/Botocudo M/' $panel.ped
sed -i 's/.hg.*realigned / /' $panel.ped

for id in `awk '{print $1}' $panel.poplist`; do
pop=`awk -v r=$id '{if(r==$2)print $1}' $panel.poplist`;
awk -v pop="$pop" -v id="$id" '{if($2==id){$6=pop; print $0}}' $panel.ped ; done > $panel.pop.ped


cp $panel.map $panel.pop.map

##Make a text file (Reference.poplist) that contains just one line saying REF

#to make par file (one line):
echo -e  poplistname: $panel.poplist"\n"\
lsqproject: YES"\n"\
genotypename: $panel.pop.ped"\n"\
snpname: $panel.pop.map"\n"\
indivname: $panel.pop.ped"\n"\
evecoutname: $panel.lsq.evec"\n"\
evaloutname: $panel.lsq.eval \
> $panel.lsqproject.par

###Run smartpca


module load eigensoft/6.0.1.1
smartpca -p $panel.lsqproject.par > $panel.lsqproject.out

###To make the plot of the PCA you will need the .evec and .eval files generated
###And remember to have a text file with the information of all of the individuals used
###i.e. file NatMex.txt




exit;
