input_files:
    # SpCave: "/users/dcruzdav/wally_americas/Panels/Moreno2018/BAM/AHUR_2064_final.bam"
    # MN0008_L3U: "/users/dcruzdav/wally_americas/Botocudos/BAM/2019_11_08/MN0008/MN0008_L3U.hg19.bam"
    # MN0008_non_U_trim5: "/users/dcruzdav/wally_americas/Botocudos/BAM/Trimmed/2020_03_10/MN0008_non_U.hg19_trim5.bam"
    # MN0008_trim_2bp_L3U_5bp_non_U:  "/users/dcruzdav/wally_americas/Botocudos/BAM/Trimmed/2020_03_10/MN0008_trim_2bp_L3U_5bp_non_U.hg19.bam"
    # MN0008_L3U_trim2:  "/users/dcruzdav/wally_americas/Botocudos/BAM/Trimmed/2020_03_10/MN0008_L3U.hg19_trim2.bam"
    # Karitiana_HGDP_TeamAB: "/users/dcruzdav/wally_americas/Panels/TeamAB_fclement/HGDP00998.flt.sort.rmdup.realign.md.bam"
    # SuruiA: "/users/dcruzdav/wally_americas/Panels/fromVictor/Modern/SuruiA.bam"
    # SuruiB: "/users/dcruzdav/wally_americas/Panels/fromVictor/Modern/SuruiB.bam"
    MayaG: "/users/dcruzdav/wally_americas/Panels/fromVictor/Modern/MayaG.bam"
    MayaH: "/users/dcruzdav/wally_americas/Panels/fromVictor/Modern/MayaH.bam"
    # DNK02: "/users/dcruzdav/americas/Panels/TeamAB_fclement/DNK02.hg19.flt.sort.rmdup.realign.md.bam"
    # HGDP00456: "/users/dcruzdav/americas/Panels/TeamAB_fclement/HGDP00456.flt.sort.rmdup.realign.md.bam"
    # HGDP00521: "/users/dcruzdav/americas/Panels/TeamAB_fclement/HGDP00521.flt.sort.rmdup.realign.md.bam"
    # HGDP00542: "/users/dcruzdav/americas/Panels/TeamAB_fclement/HGDP00542.flt.sort.rmdup.realign.md.bam"
    # HGDP00665: "/users/dcruzdav/americas/Panels/TeamAB_fclement/HGDP00665.flt.sort.rmdup.realign.md.bam"
    # HGDP00778: "/users/dcruzdav/americas/Panels/TeamAB_fclement/HGDP00778.flt.sort.rmdup.realign.md.bam"
    # HGDP00927: "/users/dcruzdav/americas/Panels/TeamAB_fclement/HGDP00927.flt.sort.rmdup.realign.md.bam"
    # HGDP00998: "/users/dcruzdav/americas/Panels/TeamAB_fclement/HGDP00998.flt.sort.rmdup.realign.md.bam"
    # HGDP01029: "/users/dcruzdav/americas/Panels/TeamAB_fclement/HGDP01029.flt.sort.rmdup.realign.md.bam"
    # HGDP01284: "/users/dcruzdav/americas/Panels/TeamAB_fclement/HGDP01284.flt.sort.rmdup.realign.md.bam"
    # HGDP01307: "/users/dcruzdav/americas/Panels/TeamAB_fclement/HGDP01307.flt.sort.rmdup.realign.md.bam"
    # SS6004467: "/users/dcruzdav/americas/Panels/TeamAB_fclement/SS6004467-dedup.rg.bam"
    # SS6004467H: "/users/dcruzdav/americas/Panels/TeamAB_fclement/SS6004467H-dedup.rg.bam"
    # SS6004468: "/users/dcruzdav/americas/Panels/TeamAB_fclement/SS6004468-dedup.rg.bam"
    # SS6004468H: "/users/dcruzdav/americas/Panels/TeamAB_fclement/SS6004468H-dedup.rg.bam"
    # SS6004469: "/users/dcruzdav/americas/Panels/TeamAB_fclement/SS6004469-dedup.rg.bam"
    # SS6004469H: "/users/dcruzdav/americas/Panels/TeamAB_fclement/SS6004469H-dedup.rg.bam"
    # SS6004470: "/users/dcruzdav/americas/Panels/TeamAB_fclement/SS6004470-dedup.rg.bam"
    # SS6004471: "/users/dcruzdav/americas/Panels/TeamAB_fclement/SS6004471-dedup.rg.bam"
    # SS6004472: "/users/dcruzdav/americas/Panels/TeamAB_fclement/SS6004472-dedup.rg.bam"
    # SS6004473: "/users/dcruzdav/americas/Panels/TeamAB_fclement/SS6004473-dedup.rg.0.0457.bam"
    # SS6004473: "/users/dcruzdav/americas/Panels/TeamAB_fclement/SS6004473-dedup.rg.bam"
    # SS6004474: "/users/dcruzdav/americas/Panels/TeamAB_fclement/SS6004474-dedup.rg.bam"
    # SS6004475: "/users/dcruzdav/americas/Panels/TeamAB_fclement/SS6004475-dedup.rg.bam"
    # SS6004476: "/users/dcruzdav/americas/Panels/TeamAB_fclement/SS6004476-dedup.rg.bam"
    # SS6004477: "/users/dcruzdav/americas/Panels/TeamAB_fclement/SS6004477-dedup.rg.bam"
    # SS6004478: "/users/dcruzdav/americas/Panels/TeamAB_fclement/SS6004478-dedup.rg.bam"
    # SS6004479: "/users/dcruzdav/americas/Panels/TeamAB_fclement/SS6004479-dedup.rg.bam"
    # SS6004480: "/users/dcruzdav/americas/Panels/TeamAB_fclement/SS6004480-dedup.rg.bam"

    
    # Aymara: "/users/dcruzdav/americas/fromVictor/Modern/Aymara.bam"
    # Chane: "/users/dcruzdav/americas/fromVictor/Modern/Chane.bam"
    # French: "/users/dcruzdav/americas/fromVictor/Modern/French.bam"
    # Han: "/users/dcruzdav/americas/fromVictor/Modern/Han.bam"
    # Huichol: "/users/dcruzdav/americas/fromVictor/Modern/Huichol.bam"
    # Karitiana: "/users/dcruzdav/americas/fromVictor/Modern/Karitiana.bam"
    # KaritianaB: "/users/dcruzdav/americas/fromVictor/Modern/KaritianaB.bam"
    # KaritianaBI16: "/users/dcruzdav/americas/fromVictor/Modern/KaritianaBI16.bam"
    # KaritianaG: "/users/dcruzdav/americas/fromVictor/Modern/KaritianaG.bam"
    # KaritianaH: "/users/dcruzdav/americas/fromVictor/Modern/KaritianaH.bam"
    # MayaG: "/users/dcruzdav/americas/fromVictor/Modern/MayaG.bam"
    # MayaH: "/users/dcruzdav/americas/fromVictor/Modern/MayaH.bam"
    # Mixe: "/users/dcruzdav/americas/fromVictor/Modern/Mixe.bam"
    # MixeE: "/users/dcruzdav/americas/fromVictor/Modern/MixeE.bam"
    # MixeF: "/users/dcruzdav/americas/fromVictor/Modern/MixeF.bam"
    # Papuan: "/users/dcruzdav/americas/fromVictor/Modern/Papuan.bam"
    # Piapoco: "/users/dcruzdav/americas/fromVictor/Modern/Piapoco.bam"
    # PimaCEPH: "/users/dcruzdav/americas/fromVictor/Modern/PimaCEPH.bam"
    # PimaE: "/users/dcruzdav/americas/fromVictor/Modern/PimaE.bam"
    # PimaF: "/users/dcruzdav/americas/fromVictor/Modern/PimaF.bam"
    # Quechua: "/users/dcruzdav/americas/fromVictor/Modern/Quechua.bam"
    # SuruiA: "/users/dcruzdav/americas/fromVictor/Modern/SuruiA.bam"
    # SuruiB: "/users/dcruzdav/americas/fromVictor/Modern/SuruiB.bam"
    # WCD01: "/users/dcruzdav/americas/fromVictor/Modern/WCD01.bam"
    # WCD02: "/users/dcruzdav/americas/fromVictor/Modern/WCD02.bam"
    # WCD03: "/users/dcruzdav/americas/fromVictor/Modern/WCD03.bam"
    # WCD04: "/users/dcruzdav/americas/fromVictor/Modern/WCD04.bam"
    # WCD05: "/users/dcruzdav/americas/fromVictor/Modern/WCD05.bam"
    # WCD08: "/users/dcruzdav/americas/fromVictor/Modern/WCD08.bam"
    # WCD13: "/users/dcruzdav/americas/fromVictor/Modern/WCD13.bam"
    # Yoruba: "/users/dcruzdav/americas/fromVictor/Modern/Yoruba.bam"
    # Yukpa: "/users/dcruzdav/americas/fromVictor/Modern/Yukpa.bam"
    # "MN0008_non_U": "/users/dcruzdav/wally_americas/Botocudos/BAM/2019_11_08/MN0008/MN0008_non_U.hg19.bam",
    # "MN0008": "/users/dcruzdav/wally_americas/Botocudos/BAM/2019_11_08/MN0008/MN0008.hg19.bam",
    # "MN00013": "/users/dcruzdav/wally_americas/Botocudos/BAM/2019_11_08/MN00013/MN00013.hg19.bam",
    # "MN00056": "/users/dcruzdav/wally_americas/Botocudos/BAM/2019_11_08/MN00056/MN00056.hg19.bam",
    # "SpCave" :"/users/dcruzdav/wally_americas/Panels/fromVictor/Ancient/SpCave.bam",
    # "LagoaSta" :"/users/dcruzdav/wally_americas/Panels/fromVictor/Ancient/LagoaSta.bam",
    # "KaritianaBI16": "/users/dcruzdav/wally_americas/Panels/fromVictor/Modern/KaritianaBI16.bam",
    # "Papuan_TeamAB": "/users/dcruzdav/wally_americas/Panels/TeamAB_fclement/HGDP00542.flt.sort.rmdup.realign.md.bam",
    # "French_TeamAB": "/users/dcruzdav/wally_americas/Panels/TeamAB_fclement/SS6004468-dedup.rg.bam",
    # Aconcagua: "/users/dcruzdav/americas/fromVictor/Ancient/Aconcagua.bam",
    # "AncKaweskar2": "/users/dcruzdav/americas/fromVictor/Ancient/AncKaweskar2.bam",
    # "AncKaweskar3": "/users/dcruzdav/americas/fromVictor/Ancient/AncKaweskar3.bam",
    # "AncYamana2": "/users/dcruzdav/americas/fromVictor/Ancient/AncYamana2.bam",
    # "AncYamana": "/users/dcruzdav/americas/fromVictor/Ancient/AncYamana.bam",
    # "Andaman": "/users/dcruzdav/americas/fromVictor/Ancient/Andaman.bam",
    # "Anzick1": "/users/dcruzdav/americas/fromVictor/Ancient/Anzick1.bam",
    # "Ayayema": "/users/dcruzdav/americas/fromVictor/Ancient/Ayayema.bam",
    # "CK09": "/users/dcruzdav/americas/fromVictor/Ancient/CK09.bam",
    # "CK10": "/users/dcruzdav/americas/fromVictor/Ancient/CK10.bam",
    # "CK13": "/users/dcruzdav/americas/fromVictor/Ancient/CK13.bam",
    # "LagoaSta": "/users/dcruzdav/americas/fromVictor/Ancient/LagoaSta.bam",
    # "Lovelock2": "/users/dcruzdav/americas/fromVictor/Ancient/Lovelock2.bam",
    # "Lovelock3": "/users/dcruzdav/americas/fromVictor/Ancient/Lovelock3.bam",
    # "LS4": "/users/dcruzdav/americas/fromVictor/Ancient/LS4.bam",
    # "LS6": "/users/dcruzdav/americas/fromVictor/Ancient/LS6.bam",
    # "LS7": "/users/dcruzdav/americas/fromVictor/Ancient/LS7.bam",
    # "LS8": "/users/dcruzdav/americas/fromVictor/Ancient/LS8.bam",
    # "LU01": "/users/dcruzdav/americas/fromVictor/Ancient/LU01.bam",
    # "LU02": "/users/dcruzdav/americas/fromVictor/Ancient/LU02.bam",
    # "LU06": "/users/dcruzdav/americas/fromVictor/Ancient/LU06.bam",
    # "PtaStaAna": "/users/dcruzdav/americas/fromVictor/Ancient/PtaStaAna.bam",
    # "SpCave": "/users/dcruzdav/americas/fromVictor/Ancient/SpCave.bam",
    # "Taino": "/users/dcruzdav/americas/fromVictor/Ancient/Taino.bam",
    # "USR1": "/users/dcruzdav/americas/fromVictor/Ancient/USR1.bam" 
